### ISSUE TITLE
Add globus logout to goauth provider

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/webauthn#16]
Apparently, issuing a `GET` on `https://auth.globus.org/v2/web/logout` with an optional `redirect_uri` query parameter can end the Globus authentication cookie which otherwise keeps a browser logged in persistently.

We should try to introduce this as a client redirect step in our webauthn flow to prevent auto-login when we intend user identity challenge.

I suggest adding it to the `GET preauth` response flow so that we attempt to zero out the client's Globus identity before sending them to Globus to login, if this will work in practice.  Another option would be to do it as part of the `DELETE session` flow, though this seems more prone to race conditions.

This may require some changes to the internal provider APIs to allow a provider to introduce an optional redirect to those existing APIs while existing providers skip this.

**Comment by ljpearlman** [comment]
Implemented in globus_auth, not goauth.

**Comment by karlcz** [comment]
We can experience this end-to-end on dev.isrd.isi.edu with UI integration and it is pretty ugly... not sure whether we want to keep this issue open or file some other issue to track upstream changes to the globus logout page flow?

**Comment by ljpearlman** [comment]
I don't like either of those alternatives, because that means there's going to be an issue sitting open potentially forever with no progress being made until Globus makes a change that they currently don't intend to make. So I'd prefer to try to make the best of what's there now.

There are probably some ways to make the user experience a little better (@hongsudt and I talked about this earlier), but those are mostly UI changes, and it might make sense to get advice from @crisaless and maybe even do some user testing.
