### ISSUE TITLE
duplicate put webauthn log messages

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/webauthn#63]
It seems like the PUT requests are being logged twice in syslog.. 

example log entry: 

276429257,,2017-10-13 12:34:28,2017-10-13 12:34:28,17,6,www.rebuildingakidney.org," {""elapsed"":0.002, ""req"":""JssJg/l0wpM="", ""scheme"":""https"", ""host"":""www-gudmap3.gudmap.org"", ""status"":""200 OK"", ""method"":""PUT"", ""path"":""/authn/session"", ""client"":""128.9.132.202"", ""user"":{""display_name"":""cristina@globusid.org"", ""identities"":[""https://auth.globus.org/abafeea0-d274-11e5-b053-4fd04d061aa4""
, ""https://auth.globus.org/339176ee-c251-4f68-b157-d477c5522b92"", ""https://auth.globus.org/3ca07fb2-cbb8-42ff-91f5-ec345296459e""], ""id"":""https://auth.globus.org/abafeea0-d274-11e5-b053-4fd04d061aa4"", ""full_name"":""Cristina Williams"", ""email"":""cristina@isi.edu""}, ""session"":{""since"":""2017-10-13 11:14:05.815596-07:00"", ""expires"":""2017-10-13 13:04:26.554617-07:00""}}",,,,,,,,,,,,1,webauthn[15232.140215
901816576]:,,,

**Comment by karlcz** [comment]
we should confirm that it's really a duplicate entry (same random request ID).  if so, there is probably an explicit log invocation in the PUT method handler and also a shared one that is also handling GET etc?

**Comment by karlcz** [comment]
I think this is due to the PUT method proxying to the GET method handler and both of them activating the same logging mechanism.

**Comment by karlcz** [comment]
I pushed a tiny change to webauthn to fix this.  once you have the updated code running, you should see that a PUT on /authn/session only produces one log message. @hongsudt

**Comment by karlcz** [comment]
@ljpearlman  I was trying to verify that this fix worked by logging myself in on www.rebuildingakidney.org, however I am now more confused than ever.

I don't see the duplication of identical log messages anymore, so I think my fix worked as intended. That was where the PUT method called the GET method and they both have the same decorator that logs an event to syslog.

But I do see qty 3 logged events for the PUT, each with different webauthn-issued request IDs, and timestamps within a second or two of each other. These seem to be originated from the webserver rather than my client machine, so I guess those are issued by mod_webauthn?  Shouldn't these be coalesced into a single request since they are so close together?  Or is there some split caching issue where, where different mod_webauthn workers are operating concurrently?

Meanwhile, I wonder what event corresponds to the actual login in this case with oauth.  Is it the GET with the `state` and `code` query parameters in the session URL?
